version: '3.7'

services:

  app:
    container_name: authors
    build: 
        context: .
        target: dev
    # volumes:
    #   - ./src:/var/www/html
    ports:
      - '8080:80'


# docker-compose up --build -d
# docker-compose down --volumes