services:
  authors:
    unique_name: authors-95d8427e
    enable: true
    ingress: true
    name: "authors"
    service:
      name: "authorservice"
    image: docker.pkg.github.com/bruno-teksial/authors/authors
    pullSecret: devspace-auth-docker-pkg-github-com
    pullPolicy: Always
    port: 80
    target: 80
    api: "/authors"